exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('birdAttributes').del()
    .then(function () {
      // Inserts seed entries
      return knex('birdAttributes').insert([
        {
          birdId: 001,
          commonName: 'Haast tokoeka kiwi',
          latinName: 'Apteryx australis',
          birdOrder: 'Casuariiformes',
          nzStatus: 'Endemic',
          conservationStatus: 'Nationally Endangered',
          length: '45 cm',
          weight: 'M: 2.4 kg | F: 3.1 kg',
          description: 'A large brown kiwi with rufous to dark brown soft feathers streaked with brown and black, a long pale bill, and short pale legs and toes.',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/southern-brown-kiwi'
        },
        {
          birdId: 002,
          commonName: 'Rowi | Okarito brown kiwi',
          latinName: 'Apteryx rowi',
          birdOrder: 'Casuariiformes',
          nzStatus: 'Endemic',
          conservationStatus: 'Nationally Vulnerable',
          length: '40 cm',
          weight: 'M: 1.9 kg | F: 2.6 kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/okarito-brown-kiwi'
        },
        {
          birdId: 003,
          commonName: 'North Island brown kiwi',
          latinName: 'Apteryx mantelli',
          birdOrder: 'Casuariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: '',
          weight: 'M: x kg | F: x kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/north-island-brown-kiwi'
        },
        {
          birdId: 004,
          commonName: 'Great spotted kiwi',
          latinName: 'Apteryx haastii',
          birdOrder: 'Casuariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x kg | F: x kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/great-spotted-kiwi'
        },
        {
          birdId: 005,
          commonName: 'Little spotted kiwi',
          latinName: 'Apteryx owenii',
          birdOrder: 'Casuariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x kg | F: x kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/little-spotted-kiwi'
        },
        {
          birdId: 006,
          commonName: 'Turkey',
          latinName: 'Meleagris gallopavo',
          birdOrder: 'Galliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x kg | F: x kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/wild-turkey'
        },
        {
          birdId: 007,
          commonName: 'Indian peacock',
          latinName: 'Pavo cristatus',
          birdOrder: 'Galliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x kg | F: x kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/peafowl'
        },
        {
          birdId: 008,
          commonName: 'Pheasant',
          latinName: 'Phasianus colchicus',
          birdOrder: 'Galliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x kg | F: x kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/common-pheasant'
        },
        {
          birdId: 009,
          commonName: 'Chukar',
          latinName: 'Alectoris chukar',
          birdOrder: 'Galliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x kg | F: x kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/chukor'
        },
        {
          birdId: 010,
          commonName: 'Brown quail',
          latinName: 'Coturnix ypsilophora',
          birdOrder: 'Galliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x kg | F: x kg',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/brown-quail'
        },
        {
          birdId: 011,
          commonName: 'Helmmeted guineafowl',
          latinName: 'Numida meleagris',
          birdOrder: 'Galliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/helmeted-guineafowl'
        },
        {
          birdId: 012,
          commonName: 'California quail',
          latinName: 'Callipepla californica',
          birdOrder: 'Galliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/california-quail'
        },
        {
          birdId: 013,
          commonName: 'White swan',
          latinName: 'Cygnus olor',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/mute-swan'
        },
        {
          birdId: 014,
          commonName: 'Black swan',
          latinName: 'Cygnus atratus',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/black-swan'
        },
        {
          birdId: 015,
          commonName: 'Greylag goose',
          latinName: 'Anser anser',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/greylag-goose'
        },
        {
          birdId: 016,
          commonName: 'Canada goose',
          latinName: 'Branta canadensis',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/canada-goose'
        },
        {
          birdId: 017,
          commonName: 'Pūtangitangi | Paradise shellduck',
          latinName: 'Tadorna variegata',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/paradise-shelduck'
        },
        {
          birdId: 018,
          commonName: 'Whio | Blue duck',
          latinName: 'Hymenolaimus malacorhynchos',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/blue-duck'
        },
        {
          birdId: 019,
          commonName: 'Grey teal',
          latinName: 'Anas gracilis',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/grey-teal'
        },
        {
          birdId: 020,
          commonName: 'Pāteke | Brown teal',
          latinName: 'Anas chlorotis',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/brown-teal'
        },
        {
          birdId: 021,
          commonName: 'Mallard duck',
          latinName: 'Anas platyrhynchos',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/mallard'
        },
        {
          birdId: 022,
          commonName: 'Australasian shoveler',
          latinName: 'Anas rhynchotis',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/australasian-shoveler'
        },
        {
          birdId: 023,
          commonName: 'Pāpango | New Zealand scaup',
          latinName: 'Aythya novaeseelandiae',
          birdOrder: 'Anseriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/new-zealand-scaup'
        },
        {
          birdId: 024,
          commonName: 'Great crested grebe',
          latinName: 'Podiceps cristatus',
          birdOrder: 'Podicipediformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/australasian-crested-grebe'
        },
        {
          birdId: 025,
          commonName: 'New Zealand dabchick',
          latinName: 'Poliocephalus rufopectus',
          birdOrder: 'Podicipediformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/new-zealand-dabchick'
        },
        {
          birdId: 026,
          commonName: 'Australasian little grebe',
          latinName: 'Tachybaptus novaehollandiae',
          birdOrder: 'Podicipediformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/australasian-little-grebe'
        },
        {
          birdId: 027,
          commonName: 'Tawaki | Fiordland crested penguin',
          latinName: 'Eudyptes pachyrhynchus',
          birdOrder: 'Sphenisciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/fiordland-crested-penguin'
        },
        {
          birdId: 028,
          commonName: 'Erect-crested penguin',
          latinName: 'Eudyptes sclateri',
          birdOrder: 'Sphenisciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/erect-crested-penguin'
        },
        {
          birdId: 029,
          commonName: 'Hoiho | Yellow-eyed penguin',
          latinName: 'Megadyptes antipodes',
          birdOrder: 'Sphenisciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/yellow-eyed-penguin'
        },
        {
          birdId: 030,
          commonName: 'Kororā | Little penguin',
          latinName: 'Eudyptula minor',
          birdOrder: 'Sphenisciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/little-penguin'
        },
        {
          birdId: 031,
          commonName: 'Southern royal albatross',
          latinName: 'Diomedea epomophora',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/southern-royal-albatross'
        },
        {
          birdId: 032,
          commonName: 'Northern royal albatross',
          latinName: 'Diomedea sanfordi',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/northern-royal-albatross'
        },
        {
          birdId: 033,
          commonName: 'Wandering albatross',
          latinName: 'Diomedea exulans',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/wandering-albatross'
        },
        {
          birdId: 034,
          commonName: 'Black-browed mollymawk',
          latinName: 'Thalassarche impavida',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/campbell-black-browed-mollymawk'
        },
        {
          birdId: 035,
          commonName: 'White-capped albatross',
          latinName: 'Thalassarche cauta',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/white-capped-mollymawk'
        },
        {
          birdId: 036,
          commonName: 'Bullers albatross',
          latinName: 'Thalassarche bulleri',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/bullers-mollymawk'
        },
        {
          birdId: 037,
          commonName: 'Light-mantled albatross',
          latinName: 'Phoebetria palpebrata',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/light-mantled-sooty-albatross'
        },
        {
          birdId: 038,
          commonName: 'Northern giant petrel',
          latinName: 'Macronectes halli',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/northern-giant-petrel'
        },
        {
          birdId: 039,
          commonName: 'Cape petrel',
          latinName: 'Daption capense',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/cape-petrel'
        },
        {
          birdId: 040,
          commonName: 'Grey-faced petrel',
          latinName: 'Pterodroma macroptera',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/grey-faced-petrel'
        },
        {
          birdId: 041,
          commonName: 'Tītī | Cooks petrel',
          latinName: 'Pterodroma cookii',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/cooks-petrel'
        },
        {
          birdId: 042,
          commonName: 'Broad-billed prion',
          latinName: 'Pachyptila vittata',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/broad-billed-prion'
        },
        {
          birdId: 043,
          commonName: 'Fairy prion',
          latinName: 'Pachyptila turtur',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/fairy-prion'
        },
        {
          birdId: 044,
          commonName: 'Westland petrel',
          latinName: 'Procellaria westlandica',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/westland-petrel'
        },
        {
          birdId: 045,
          commonName: 'Black petrel',
          latinName: 'Procellaria parkinsoni',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/black-petrel'
        },
        {
          birdId: 046,
          commonName: 'Bullers shearwater',
          latinName: 'Puffinus bulleri',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/bullers-shearwater'
        },
        {
          birdId: 047,
          commonName: 'Flesh-footed shearwater',
          latinName: 'Puffinus carneipes',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/flesh-footed-shearwater'
        },
        {
          birdId: 048,
          commonName: 'Sooty shearwater',
          latinName: 'Puffinus griseus',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/sooty-shearwater'
        },
        {
          birdId: 049,
          commonName: 'Short-tailed shearwater',
          latinName: 'Puffinus tenuirostris',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/short-tailed-shearwater'
        },
        {
          birdId: 050,
          commonName: 'Huttons shearwater',
          latinName: 'Puffinus huttoni',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/huttons-shearwater'
        },
        {
          birdId: 051,
          commonName: 'Little shearwater',
          latinName: 'Puffinus assimilis',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/little-shearwater'
        },
        {
          birdId: 052,
          commonName: 'White-faced storm petrel',
          latinName: 'Pelagodroma marina',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/white-faced-storm-petrel'
        },
        {
          birdId: 053,
          commonName: 'New Zealand storm petrel',
          latinName: 'Fregetta maoriana',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/new-zealand-storm-petrel'
        },
        {
          birdId: 054,
          commonName: 'Common diving petrel',
          latinName: 'Pelecanoides urinatrix',
          birdOrder: 'Procellariiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/common-diving-petrel'
        },
        {
          birdId: 055,
          commonName: 'Red-tailed tropicbird',
          latinName: 'Phaethon rubricauda',
          birdOrder: 'Phaethontiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/red-tailed-tropicbird'
        },
        {
          birdId: 056,
          commonName: 'Australian pelican',
          latinName: 'Pelecanus conspicillatus',
          birdOrder: 'Pelecaniformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/australian-pelican'
        },
        {
          birdId: 057,
          commonName: 'Tākapu | Australasian gannet',
          latinName: 'Morus serrator',
          birdOrder: 'Suliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/australasian-gannet'
        },
        {
          birdId: 058,
          commonName: 'Masked booby',
          latinName: 'Sula dactylatra',
          birdOrder: 'Suliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/masked-booby'
        },
        {
          birdId: 059,
          commonName: 'Little shag',
          latinName: 'Phalacrocorax melanoleucos',
          birdOrder: 'Suliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/little-shag'
        },
        {
          birdId: 060,
          commonName: 'Black shag',
          latinName: 'Phalacrocorax carbo',
          birdOrder: 'Suliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/black-shag'
        },
        {
          birdId: 061,
          commonName: 'Pied shag',
          latinName: 'Phalacrocorax varius',
          birdOrder: 'Suliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/pied-shag'
        },
        {
          birdId: 062,
          commonName: 'Little black shag',
          latinName: 'Phalacrocorax sulcirostris',
          birdOrder: 'Suliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/little-black-shag'
        },
        {
          birdId: 063,
          commonName: 'New Zealand King shag',
          latinName: 'Leucocarbo carunculatus',
          birdOrder: 'Suliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/new-zealand-king-shag'
        },
        {
          birdId: 064,
          commonName: 'Spotted shag',
          latinName: 'Stictocarbo punctatus',
          birdOrder: 'Suliformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/spotted-shag'
        },
        {
          birdId: 065,
          commonName: 'Kōtuku | White heron',
          latinName: 'Ardea alba modesta',
          birdOrder: 'Ciconiiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/white-heron'
        },
        {
          birdId: 066,
          commonName: 'White-faced heron',
          latinName: 'Egretta novaehollandiae',
          birdOrder: 'Ciconiiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/white-faced-heron'
        },
        {
          birdId: 067,
          commonName: 'Australasian bittern',
          latinName: 'Botaurus poiciloptilus',
          birdOrder: 'Ciconiiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/australasian-bittern'
        },
        {
          birdId: 068,
          commonName: 'Royal spoonbill',
          latinName: 'Platalea regia',
          birdOrder: 'Ciconiiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/royal-spoonbill'
        },
        {
          birdId: 069,
          commonName: 'Kāhu | Australasian harrier hawk',
          latinName: 'Circus approximans',
          birdOrder: 'Accipitriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/swamp-harrier'
        },
        {
          birdId: 070,
          commonName: 'Kārearea | New Zealand falcon',
          latinName: 'Falco novaseelandiae',
          birdOrder: 'Falconiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/new-zealand-falcon'
        },
        {
          birdId: 071,
          commonName: 'Banded rail',
          latinName: 'Gallirallus philippensis',
          birdOrder: 'Gruiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/banded-rail'
        },
        {
          birdId: 072,
          commonName: 'Weka',
          latinName: 'Gallirallus australis',
          birdOrder: 'Gruiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/weka'
        },
        {
          birdId: 073,
          commonName: 'Spotless crake',
          latinName: 'Porzana tabuensis',
          birdOrder: 'Gruiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/spotless-crake'
        },
        {
          birdId: 074,
          commonName: 'Pukeko',
          latinName: 'Porphyrio melanotus',
          birdOrder: 'Gruiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/pukeko'
        },
        {
          birdId: 075,
          commonName: 'Takahē',
          latinName: 'Porphyrio hochstetteri',
          birdOrder: 'Gruiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/south-island-takahe'
        },
        {
          birdId: 076,
          commonName: 'Australian coot',
          latinName: 'Fulica atra',
          birdOrder: 'Gruiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/australian-coot'
        },
        {
          birdId: 077,
          commonName: 'Red knot',
          latinName: 'Calidris canutus',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/lesser-knot'
        },
        {
          birdId: 078,
          commonName: 'Bar-tailed godwit',
          latinName: 'Limosa lapponica',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/bar-tailed-godwit'
        },
        {
          birdId: 079,
          commonName: 'Variable oystercatcher',
          latinName: 'Haematopus unicolor',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/variable-oystercatcher'
        },
        {
          birdId: 080,
          commonName: 'Pied oystercatcher',
          latinName: 'Haematopus finschi',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/south-island-pied-oystercatcher'
        },
        {
          birdId: 081,
          commonName: 'Pied stilt',
          latinName: 'Himantopus himantopus',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/pied-stilt'
        },
        {
          birdId: 082,
          commonName: 'Kakī | Black stilt',
          latinName: 'Himantopus novaezelandiae',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/black-stilt'
        },
        {
          birdId: 083,
          commonName: 'New Zealand dotterel',
          latinName: 'Charadrius oscurus',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/new-zealand-dotterel'
        },
        {
          birdId: 084,
          commonName: 'Banded dotterel',
          latinName: 'Charadrius bicinctus',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/banded-dotterel'
        },
        {
          birdId: 085,
          commonName: 'Wrybill',
          latinName: 'Anarhynchus frontalis',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/wrybill'
        },
        {
          birdId: 086,
          commonName: 'Black-fronted dotterel',
          latinName: 'Elseyornis melanops',
          birdOrder: 'Charadriiformes',
          nzStatus: 'http://nzbirdsonline.org.nz/species/black-fronted-dotterel',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: ''
        },
        {
          birdId: 087,
          commonName: 'Shore plover',
          latinName: 'Thinornis novaeseelandiae',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/shore-plover'
        },
        {
          birdId: 088,
          commonName: 'Spur-winged plover',
          latinName: 'Vanellus miles novaehollandiae',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/spur-winged-plover'
        },
        {
          birdId: 089,
          commonName: 'Southern skua',
          latinName: 'Catharacta antarctica lonnbergi',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/subantarctic-skua'
        },
        {
          birdId: 090,
          commonName: 'Black-backed gull',
          latinName: 'Larus dominicanus',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/southern-black-backed-gull'
        },
        {
          birdId: 091,
          commonName: 'Red-billed gull',
          latinName: 'Larus scopulinus',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/red-billed-gull'
        },
        {
          birdId: 092,
          commonName: 'Black-billed gull',
          latinName: 'Larus bulleri',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/black-billed-gull'
        },
        {
          birdId: 093,
          commonName: 'Fairy tern',
          latinName: 'Sternula nereis davisae',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/fairy-tern'
        },
        {
          birdId: 094,
          commonName: 'Caspian tern',
          latinName: 'Hydroprogne caspia',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/caspian-tern'
        },
        {
          birdId: 095,
          commonName: 'Black-fronted tern',
          latinName: 'Chlidonias albostriatus',
          birdOrder: 'Charadriiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/black-fronted-tern'
        },
        {
          birdId: 096,
          commonName: 'Rock pigeon',
          latinName: 'Columba livia',
          birdOrder: 'Columbiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/rock-pigeon'
        },
        {
          birdId: 097,
          commonName: 'Ring-necked dove',
          latinName: 'Streptopelia risoria',
          birdOrder: 'Columbiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/barbary-dove'
        },
        {
          birdId: 098,
          commonName: 'Kererū',
          latinName: 'Hemiphaga novaesselandiae',
          birdOrder: 'Columbiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/new-zealand-pigeon'
        },
        {
          birdId: 099,
          commonName: 'Kakapō',
          latinName: 'Strigops habroptilus',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/kakapo'
        },
        {
          birdId: 100,
          commonName: 'Kākā',
          latinName: 'Nestor meridionalis',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/kaka'
        },
        {
          birdId: 101,
          commonName: 'Kea',
          latinName: 'Nestor notabilis',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/kea'
        },
        {
          birdId: 102,
          commonName: 'Sulphur-crested cockatoo',
          latinName: 'Cacatua galerita',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/sulphur-crested-cockatoo'
        },
        {
          birdId: 103,
          commonName: 'Eastern rosella',
          latinName: 'Platycercus eximius',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/eastern-rosella'
        },
        {
          birdId: 104,
          commonName: 'Crimson rosella',
          latinName: 'Platycercus elegans',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/crimson-rosella'
        },
        {
          birdId: 105,
          commonName: 'Red-crowned kākāriki',
          latinName: 'Cyanoramphus novaezelandiae',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/red-crowned-parakeet'
        },
        {
          birdId: 106,
          commonName: 'Yellow-crowned kākāriki',
          latinName: 'Cyanoramphus auriceps',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/yellow-crowned-parakeet'
        },
        {
          birdId: 107,
          commonName: 'Orange-fronted kākāriki',
          latinName: 'Cyanoramphus malherbi',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/orange-fronted-parakeet'
        },
        {
          birdId: 108,
          commonName: 'Antipodes Island parakeet',
          latinName: 'Cyanoramphus unicolor',
          birdOrder: 'Psittaciformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/antipodes-island-parakeet'
        },
        {
          birdId: 109,
          commonName: 'Shining cuckoo',
          latinName: 'Chalcites lucidus',
          birdOrder: 'Cuculiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/shining-cuckoo'
        },
        {
          birdId: 110,
          commonName: 'Long-tailed cuckoo',
          latinName: 'Eudynamys taitensis',
          birdOrder: 'Cuculiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/long-tailed-cuckoo'
        },
        {
          birdId: 111,
          commonName: 'Ruru | Morepork',
          latinName: 'Ninox novaeseelandiae',
          birdOrder: 'Strigiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/morepork'
        },
        {
          birdId: 112,
          commonName: 'Little owl',
          latinName: 'Anthene noctua',
          birdOrder: 'Strigiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/little-owl'
        },
        {
          birdId: 113,
          commonName: 'Barn owl',
          latinName: 'Tyto javanica',
          birdOrder: 'Strigiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/barn-owl'
        },
        {
          birdId: 114,
          commonName: 'Laughing kookaburra',
          latinName: 'Dacelo novaeguineae',
          birdOrder: 'Coraciiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/laughing-kookaburra'
        },
        {
          birdId: 115,
          commonName: 'Kōtare | Kingfisher',
          latinName: 'Todiramphus sanctus',
          birdOrder: 'Coraciiformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/sacred-kingfisher'
        },
        {
          birdId: 116,
          commonName: 'Rifleman',
          latinName: 'Acanthisitta chloris',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/rifleman'
        },
        {
          birdId: 117,
          commonName: 'Rock wren',
          latinName: 'Xenicus gilviventris',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/rock-wren'
        },
        {
          birdId: 118,
          commonName: 'North Island kōkako',
          latinName: 'Callaeas wilsoni',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/north-island-kokako'
        },
        {
          birdId: 119,
          commonName: 'North Island tīeke | saddleback',
          latinName: 'Philesturnus rufusater',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/north-island-saddleback'
        },
        {
          birdId: 120,
          commonName: 'South Island tīeke | saddleback',
          latinName: 'Philesturnus carunculatus',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/south-island-saddleback'
        },
        {
          birdId: 121,
          commonName: 'Hīhī | Stitchbird',
          latinName: 'Notiomystis cincta',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/stitchbird'
        },
        {
          birdId: 122,
          commonName: 'Grey warbler',
          latinName: 'Gerygone igata',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/grey-warbler'
        },
        {
          birdId: 123,
          commonName: 'Korimako | Bellbird',
          latinName: 'Anthornis melanura',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/bellbird'
        },
        {
          birdId: 124,
          commonName: 'Tūī',
          latinName: 'Prosthemadera novaeseelandiae',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/tuiv'
        },
        {
          birdId: 125,
          commonName: 'Whitehead',
          latinName: 'Mohoua albicilla',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/whitehead'
        },
        {
          birdId: 126,
          commonName: 'Mohua | Yellowhead',
          latinName: 'Mohoua ochrocephala',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/yellowhead'
        },
        {
          birdId: 127,
          commonName: 'Pīpipi | Brown creeper',
          latinName: 'Mohoua novaeseelandiae',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/brown-creeper'
        },
        {
          birdId: 128,
          commonName: 'Australian magpie',
          latinName: 'Gymnorhina tibicen',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/australian-magpie'
        },
        {
          birdId: 129,
          commonName: 'Pīwakawaka | Fantail',
          latinName: 'Rhipidura fuliginosa',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/new-zealand-fantail'
        },
        {
          birdId: 130,
          commonName: 'Rook',
          latinName: 'Corvus frugilegus',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/rook'
        },
        {
          birdId: 131,
          commonName: 'Miromiro | Tomtit',
          latinName: 'Petroica macrocephala',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/tomtit'
        },
        {
          birdId: 132,
          commonName: 'North Island robin',
          latinName: 'Petroica longipes',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/north-island-robin'
        },
        {
          birdId: 133,
          commonName: 'South Island robin',
          latinName: 'Petroica australis',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/south-island-robin'
        },
        {
          birdId: 134,
          commonName: 'Black robin',
          latinName: 'Petroica traversi',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/black-robin'
        },
        {
          birdId: 135,
          commonName: 'Skylark',
          latinName: 'Alauda arvensis',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/eurasian-skylark'
        },
        {
          birdId: 136,
          commonName: 'Fernbird',
          latinName: 'Bowdleria punctata',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/fernbird'
        },
        {
          birdId: 137,
          commonName: 'Tauhou | Silvereye',
          latinName: 'Zosterops lateralis',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/silvereye'
        },
        {
          birdId: 138,
          commonName: 'Barn swallow',
          latinName: 'Hirundo neoxena',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/welcome-swallow'
        },
        {
          birdId: 139,
          commonName: 'Blackbird',
          latinName: 'Manu pango',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/eurasian-blackbird'
        },
        {
          birdId: 140,
          commonName: 'Song thrush',
          latinName: 'Turdus philomelos',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/song-thrush'
        },
        {
          birdId: 141,
          commonName: 'Starling',
          latinName: 'Sturnus vulgaris',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/common-starling'
        },
        {
          birdId: 142,
          commonName: 'Common myna',
          latinName: 'Acridotheres tristis',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/common-myna'
        },
        {
          birdId: 143,
          commonName: 'Sparrow',
          latinName: 'Passer domesticus',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/house-sparrow'
        },
        {
          birdId: 144,
          commonName: 'Pipit',
          latinName: 'Anthus novaeseelandiae',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://www.nzbirdsonline.org.nz/species/new-zealand-pipit'
        },
        {
          birdId: 145,
          commonName: 'Dunnock',
          latinName: 'Prunella modularis',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://www.nzbirdsonline.org.nz/species/dunnock'
        },
        {
          birdId: 146,
          commonName: 'Chaffinch',
          latinName: 'Fingilla coelebs',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://www.nzbirdsonline.org.nz/species/chaffinch'
        },
        {
          birdId: 147,
          commonName: 'Goldfinch',
          latinName: 'Carduelis carduelis',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/european-goldfinch'
        },
        {
          birdId: 148,
          commonName: 'Greenfinch',
          latinName: 'Carduelis chloris',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/european-greenfinch'
        },
        {
          birdId: 149,
          commonName: 'Redpoll',
          latinName: 'Carduelis flammea',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/common-redpoll'
        },
        {
          birdId: 150,
          commonName: 'Yellowhammer',
          latinName: 'Emberiza citronella',
          birdOrder: 'Passeriformes',
          nzStatus: '',
          conservationStatus: '',
          length: 'M: x cm | F: x cm',
          weight: 'M: x g | F: x g',
          description: '',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/yellowhammer'
        },
        {
          birdId: 151,
          commonName: 'Haast eagle',
          latinName: 'Hieraaetus moorei',
          birdOrder: 'Accipitriformes',
          nzStatus: 'Endemic',
          conservationStatus: 'Extinct',
          length: '1.4 m',
          weight: 'M: 12 kg | F: 18 kg',
          description: 'Giant eagle with large wingspan, head, bill, legs and talons. Māori oral tradition records that it had black feathers tinged with yellow or green and a bunch of red feathers on its head.',
          image: '#',
          audio: '#',
          url: 'http://nzbirdsonline.org.nz/species/haasts-eagle'
        }
      ])
    })
}
